site_name: "Инструменты исследователя"
site_url: https://research-instruments.github.io
repo_url: https://github.com/research-instruments/website

nav:
  - Главная: index.md  # ____.md is the markdown file stored in docs folder with the content of a page
  - Компетенции исследователя:
    - skills.md
    - Личностное развитие (soft-skills):
      - Кругозор: share.md
      - Самоорганизация (тайм-менеджмент): share.md
      - Критическое мышление: share.md
    - Научная работа (hard-skills):
      - Планирование исследования: share.md
      - Работа с источниками: share.md
      - Программирование: share.md
      - Обработка результатов: share.md
      - Научная визуализация: share.md    
    - Коммуникация (soft-skills):
      - Подготовка публикаций: share.md
      - Публичные выступления: share.md
      - Дискуссии: share.md
      - Участие в исследовательских проектах: share.md
  - Сообщество:
    - network.md  # section with two subsections - FAQs and - Useful Git commands
    - Манифест открытой науки: manifest.md
    - Уроки научных вычислений:
      - Notebook page: JNotebooks/Demo.ipynb
      - Notebook page: JNotebooks/Nlopt.ipynb
    - Online-сервисы для исследователя:
      - Наукометрия: share.md
      - Работа с текстами: share.md
      - Персональный менеджмент: share.md
    - Шаблоны публикаций и конференционных постеров:
      - Шаблон диссертации: disser.md
      - Зарубежные журналы: share.md
    - Истории персонального опыта:
      - Демо: experience/template.md
      - Скрипник Александр: experience/NeutronYield.md
      - Антонов Евгений: experience/repositoriesForYoungDevelopers.md
      - Макиенко Дарья: experience/ml_math_and_programming.md
    - Поделись своим опытом: share.md
  - Рекомендуемые курсы: catalogue.md  
  - FAQ: help.md
  - Мы в GitHub: https://github.com/research-instruments

theme:
  name: material
  language: ru
  custom_dir: overrides # path to folder "overrides", where the customized home.html and footer.html are stored
  palette:
    accent: deep orange # color of element, when you hover the mouse over it
  logo: assets/favicon_min.ico # path to logo at the top left of the header
  favicon: assets/favicon_min.ico # path to favicon
  features: # the behaviour which defines the appearance of the table of contents squidfunk.github.io/mkdocs-material/setup/setting-up-navigation
    # - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.indexes # A back-to-top button
    - search.highlight
    - search.suggest
  icon: # set of icons for Inline blocks and collapsible windows squidfunk.github.io/mkdocs-material/reference/admonitions
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

copyright: © 2022 МИФИ и Консорциум Университетов # info in footer (at the bottom of each page)

extra_javascript: # paths to additional JavaScript code inside docs folder
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js # tablesort functionality
  - javascripts/tables.js # tables functionality
  - javascripts/search.js # search in tables functionality

extra_css: # paths to additional css code inside docs folder
  - stylesheets/extra.css # defines basic colors in the site scheme

plugins: 
  - search:
      lang: ru  # search table functionality
  - mkdocs-jupyter

markdown_extensions:
  - toc: # hiding table of contents to make appearance not like in docs
      toc_depth: 2  # hiding table of contents to make appearance not like in docs
  - pymdownx.tasklist:  # ability to use pretty tasklists from mkdocs-material
      clickable_checkbox: true
  - attr_list # allows to add HTML attributes and CSS classes to Markdown elements
  - abbr # add additional content to parts of the text which are then shown on hover
  - admonition # extension python-markdown.github.io/extensions/admonition
  - pymdownx.keys # allows for inserting keyboard keys as in Useful Git commands
  - pymdownx.details # ability to make admonitions collapsible
  - pymdownx.tabbed # extension facelessuser.github.io/pymdown-extensions/extensions/tabbed/
  - pymdownx.snippets # for adding code sample is intended to demonstrate programming tasks or scenarios as in Useful Git commands
  # - meta

extra:
  analytics:
    provider: google
    property: G-S54D3HMS7N
  disqus: neadb
