site_name: "Инструменты исследователя"
site_url: https://research-instruments.github.io
repo_url: https://github.com/research-instruments/website

nav:
  - Главная: index.md  # ____.md is the markdown file stored in docs folder with the content of a page
  - Блоки компетенций исследователя:
    - skills.md
    - Научные инструменты:
      - Обработка данных: competencies/data.md
      - Работа со статьями при помощи Emacs: competencies/papers_workflow_emacs.md
      - Методы научной визуализации : competencies/viz.md
      - Научные базы данных: share.md

    - IT-компетенции:
      - Программирование: competencies/it.md
      - Системы компьютерной верстки: competencies/LaTeX.md


    - Технологии коммуникации:
      - Презентация: competencies/plots.md
      - Ореn-Science: share.md
      - Иностранные языки: share.md
      - Дискуссии: competencies/disc.md
      - Networking: share.md

    - Чтение и письмо:
      - Понимание научных статей: share.md
      - Навыки написания эссе и статей: share.md
      - Рецензирование научных текстов: share.md

    - Коммерциализация науки:
      - Технологическое предпринимательство: share.md
      - Интеллектуальная собственность: share.md

    - Финансирование науки:
      - Грантовая поддержка: competencies/grants.md
      - Исследовательские проекты: share.md

    - Общество и наука:
      - Научная этика: competencies/ethics_codex.md
      - История науки: share.md
      - Перспективы развития науки: share.md

    - Видение научных задач:
      - Технологические тренды: share.md
      - Обзор развития научных областей: share.md

    - Методика  проведения исследований:
      - Теория: share.md
      - Гипотезы: share.md
      - Дизайн эксперимента: share.md


  - Сообщество:
    - network.md  # section with two subsections - FAQs and - Useful Git commands
    - Манифест открытой науки: manifest.md
    - Уроки научных вычислений:
      - Notebook page: JNotebooks/Demo.ipynb
      - Notebook page: JNotebooks/Nlopt.ipynb
      - Notebook page: JNotebooks/openmc pincell by Paul Romano.ipynb
      - Notebook page: JNotebooks/openmc candu by Paul Romano.ipynb
      - Notebook page: JNotebooks/openmc hexagonal lattice by Paul Romano.ipynb
      - Notebook page: JNotebooks/openmc SFR by Paul Romano.ipynb
      - Notebook page: JNotebooks/openmc VVER by Paul Romano.ipynb
    - Online-сервисы для исследователя:
      - Наукометрия: share.md
      - Работа с текстами: share.md
      - Персональный менеджмент: share.md
    - Шаблоны публикаций и конференционных постеров:
      - Шаблон диссертации: disser.md
      - Зарубежные журналы: share.md
    - Истории персонального опыта:
      - Демо: experience/template.md
      - Скрипник Александр: experience/NeutronYield.md
      - Антонов Евгений: experience/repositoriesForYoungDevelopers.md
      - Макиенко Дарья: experience/ml_math_and_programming.md
      - Епифанов Сергей: experience/DiagramPlotting.md
      - Суханов Михаил: experience/ProgrammingPractice.md
      - Дашанова Екатерина: experience/openmc_install.md
      - Мамаев Михаил: experience/fist_steps_in_latex.md
      - Кулямин Павел: experience/QE_Install_PC.md

    - Поделись своим опытом: share.md
  - Рекомендуемые курсы: catalogue.md  
  - FAQ: help.md
  - Мы в GitHub: https://github.com/research-instruments

theme:
  name: material
  language: ru
  custom_dir: overrides # path to folder "overrides", where the customized home.html and footer.html are stored
  palette:
    accent: deep orange # color of element, when you hover the mouse over it
  logo: assets/favicon_min.ico # path to logo at the top left of the header
  favicon: assets/favicon_min.ico # path to favicon
  features: # the behaviour which defines the appearance of the table of contents squidfunk.github.io/mkdocs-material/setup/setting-up-navigation
    # - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.indexes # A back-to-top button
    - search.highlight
    - search.suggest
  icon: # set of icons for Inline blocks and collapsible windows squidfunk.github.io/mkdocs-material/reference/admonitions
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

copyright: © 2022 МИФИ и Консорциум Университетов # info in footer (at the bottom of each page)

extra_javascript: # paths to additional JavaScript code inside docs folder
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js # tablesort functionality
  - javascripts/tables.js # tables functionality
  - javascripts/search.js # search in tables functionality

extra_css: # paths to additional css code inside docs folder
  - stylesheets/extra.css # defines basic colors in the site scheme

plugins: 
  - search:
      lang: ru  # search table functionality
  - mkdocs-jupyter

markdown_extensions:
  - toc: # hiding table of contents to make appearance not like in docs
      toc_depth: 2  # hiding table of contents to make appearance not like in docs
  - pymdownx.tasklist:  # ability to use pretty tasklists from mkdocs-material
      clickable_checkbox: true
  - attr_list # allows to add HTML attributes and CSS classes to Markdown elements
  - abbr # add additional content to parts of the text which are then shown on hover
  - admonition # extension python-markdown.github.io/extensions/admonition
  - pymdownx.keys # allows for inserting keyboard keys as in Useful Git commands
  - pymdownx.details # ability to make admonitions collapsible
  - pymdownx.tabbed # extension facelessuser.github.io/pymdown-extensions/extensions/tabbed/
  - pymdownx.snippets # for adding code sample is intended to demonstrate programming tasks or scenarios as in Useful Git commands

extra:
  analytics:
    provider: google
    property: G-S54D3HMS7N
  disqus: neadb
